import { Injectable, signal } from '@angular/core';

export type Langue = 'fr' | 'en';

/** Traducteur FR/EN léger. Usage : tr.t('menu.historique') ou tr.t('cle.avec.param', { n: 5 }) */
@Injectable({ providedIn: 'root' })
export class TraductionService {

  langue = signal<Langue>((localStorage.getItem('langue') as Langue) || 'fr');

  private readonly dictionnaire: Record<string, { fr: string; en: string }> = {
    // --- Menu / layout ---
    'menu.titre': { fr: 'MENU', en: 'MENU' },
    'menu.verification': { fr: 'Nouveau transfert', en: 'New transfer' },
    'menu.historique': { fr: 'Historique', en: 'History' },
    'menu.bilan': { fr: 'Bilan journalier', en: 'Daily summary' },
    'menu.annulation': { fr: 'Annuler un transfert', en: 'Cancel a transfer' },
    'menu.nonClotures': { fr: 'Non clôturés', en: 'Not closed' },
    'menu.admin': { fr: 'Administration', en: 'Administration' },
    'menu.espaceAdministration': { fr: 'Espace administration', en: 'Admin area' },
    'menu.deconnexion': { fr: 'Se déconnecter', en: 'Log out' },
    'layout.enLigne': { fr: 'En ligne', en: 'Online' },
    'layout.agentParDefaut': { fr: 'Agent', en: 'Agent' },
    'layout.titreDefaut': { fr: 'Suivi Plafonds', en: 'Cap Monitoring' },
    'layout.titreVerification': { fr: 'Vérification du plafond', en: 'Cap verification' },
    'layout.sousTitreVerification': { fr: 'Contrôlez le plafond mensuel Hors CEMAC avant exécution', en: 'Check the monthly non-CEMAC cap before execution' },
    'layout.titreHistorique': { fr: 'Historique des transactions', en: 'Transaction history' },
    'layout.sousTitreHistorique': { fr: 'Toutes les opérations vérifiées', en: 'All verified operations' },
    'layout.titreBilan': { fr: 'Bilan journalier', en: 'Daily summary' },
    'layout.sousTitreBilan': { fr: 'Activité du jour · Agent DRI', en: "Today's activity · DRI Agent" },
    'layout.titreAnnulation': { fr: 'Annuler un transfert exécuté', en: 'Cancel an executed transfer' },
    'layout.sousTitreAnnulation': { fr: "Sélectionnez l'opération à annuler", en: 'Select the operation to cancel' },
    'layout.titreNonClotures': { fr: 'Transferts non clôturés', en: 'Unclosed transfers' },
    'layout.sousTitreNonClotures': { fr: 'Autorisés en attente de référence plateforme', en: 'Authorised, awaiting platform reference' },
    'layout.titreDetails': { fr: "Détails de l'opération", en: 'Operation details' },
    'layout.sousTitreDetails': { fr: 'Fiche complète de la transaction', en: 'Full transaction record' },

    // --- Connexion ---
    'login.titre': { fr: 'Connexion', en: 'Sign in' },
    'login.email': { fr: 'Adresse email', en: 'Email address' },
    'login.mdp': { fr: 'Mot de passe', en: 'Password' },
    'login.bouton': { fr: 'Se connecter', en: 'Sign in' },
    'login.oubli': { fr: 'Mot de passe oublié ?', en: 'Forgot password?' },
    'login.info': { fr: 'Votre compte est créé par Afriland First Bank.', en: 'Your account is created by Afriland First Bank.' },
    'login.retourTitre1': { fr: 'Bon retour,', en: 'Welcome back,' },
    'login.retourTitre2': { fr: 'Agent.', en: 'Agent.' },
    'login.pitch': { fr: 'Connectez-vous pour suivre les plafonds de transferts rapides Hors CEMAC en temps réel.', en: 'Sign in to track non-CEMAC fast transfer caps in real time.' },
    'login.point1': { fr: 'Contrôle instantané du plafond mensuel', en: 'Instant monthly cap check' },
    'login.point2': { fr: 'Historique & bilan journalier automatisés', en: 'Automated history & daily summary' },
    'login.sousTitre': { fr: 'Renseignez vos identifiants agent.', en: 'Enter your agent credentials.' },
    'login.souvenir': { fr: 'Se souvenir de moi', en: 'Remember me' },
    'login.connexionEnCours': { fr: 'Connexion…', en: 'Signing in…' },
    'login.pasDeCompte': { fr: 'Pas encore de compte ?', en: "Don't have an account yet?" },
    'login.retourAccueil': { fr: "← Retour à l'accueil", en: '← Back to home' },
    'login.erreurIdentifiants': { fr: 'Identifiants incorrects.', en: 'Incorrect credentials.' },
    'login.accesSecurise': { fr: 'Accès sécurisé', en: 'Secure access' },
    'login.masquerMdp': { fr: 'Masquer le mot de passe', en: 'Hide password' },
    'login.afficherMdp': { fr: 'Afficher le mot de passe', en: 'Show password' },
    'login.erreurChampsRequis': { fr: 'Veuillez renseigner votre adresse e-mail et votre mot de passe.', en: 'Please enter your email address and password.' },

    // --- Inscription ---
    'register.titre1': { fr: 'Créez votre', en: 'Create your' },
    'register.titre2': { fr: 'compte agent.', en: 'agent account.' },
    'register.pitch': { fr: 'Renseignez vos informations pour accéder au suivi des plafonds de transferts rapides.', en: 'Enter your information to access fast transfer cap monitoring.' },
    'register.point1': { fr: 'Accès sécurisé réservé aux agents DRI', en: 'Secure access reserved for DRI agents' },
    'register.point2': { fr: 'Validation par votre administrateur', en: 'Validation by your administrator' },
    'register.titre': { fr: 'Créer un compte', en: 'Create an account' },
    'register.sousTitre': { fr: 'Renseignez vos informations agent.', en: 'Enter your agent information.' },
    'register.nomComplet': { fr: 'Nom complet', en: 'Full name' },
    'register.role': { fr: 'Rôle', en: 'Role' },
    'register.confirmer': { fr: 'Confirmer', en: 'Confirm' },
    'register.cgu': { fr: "J'accepte les conditions d'utilisation internes et la politique de confidentialité.", en: 'I accept the internal terms of use and the privacy policy.' },
    'register.creationEnCours': { fr: 'Création…', en: 'Creating…' },
    'register.creerMonCompte': { fr: 'Créer mon compte', en: 'Create my account' },
    'register.dejaCompte': { fr: 'Déjà un compte ?', en: 'Already have an account?' },
    'register.erreurMdpDiff': { fr: 'Les mots de passe ne correspondent pas.', en: 'Passwords do not match.' },
    'register.erreurCgu': { fr: "Veuillez accepter les conditions d'utilisation.", en: 'Please accept the terms of use.' },
    'register.succes': { fr: 'Votre compte a été créé avec succès ! Redirection vers la connexion…', en: 'Your account was created successfully! Redirecting to sign in…' },
    'register.erreurCreation': { fr: 'Impossible de créer le compte.', en: 'Unable to create the account.' },

    // --- Mot de passe oublié ---
    'forgot.titre1': { fr: 'Mot de passe', en: 'Forgot your' },
    'forgot.titre2': { fr: 'oublié ?', en: 'password?' },
    'forgot.pitch': { fr: 'Réinitialisez votre accès en toute sécurité grâce à un code envoyé par SMS sur votre numéro enregistré.', en: 'Securely reset your access with a code sent by SMS to your registered number.' },
    'forgot.point1': { fr: 'Vérification par code SMS à usage unique', en: 'Verification via one-time SMS code' },
    'forgot.point2': { fr: 'Nouveau mot de passe immédiatement actif', en: 'New password active immediately' },
    'forgot.h': { fr: 'Mot de passe oublié', en: 'Forgot password' },
    'forgot.sousTitre': { fr: 'Suivez les 3 étapes pour réinitialiser votre accès.', en: 'Follow the 3 steps to reset your access.' },
    'forgot.etape1': { fr: '1. Téléphone', en: '1. Phone' },
    'forgot.etape2': { fr: '2. Code SMS', en: '2. SMS code' },
    'forgot.etape3': { fr: '3. Nouveau mot de passe', en: '3. New password' },
    'forgot.envoiEnCours': { fr: 'Envoi en cours…', en: 'Sending…' },
    'forgot.recevoirCode': { fr: 'Recevoir le code par SMS', en: 'Receive the code by SMS' },
    'forgot.codeLabel': { fr: 'Code reçu par SMS (6 chiffres)', en: 'Code received by SMS (6 digits)' },
    'forgot.verificationEnCours': { fr: 'Vérification…', en: 'Verifying…' },
    'forgot.verifierCode': { fr: 'Vérifier le code', en: 'Verify the code' },
    'forgot.renvoyerCode': { fr: 'Renvoyer un code', en: 'Resend a code' },
    'forgot.nouveauMdp': { fr: 'Nouveau mot de passe', en: 'New password' },
    'forgot.confirmerMdp': { fr: 'Confirmer le mot de passe', en: 'Confirm password' },
    'forgot.reinitialisationEnCours': { fr: 'Réinitialisation…', en: 'Resetting…' },
    'forgot.reinitialiserBtn': { fr: 'Réinitialiser mon mot de passe', en: 'Reset my password' },
    'forgot.retourConnexion': { fr: '← Retour à la connexion', en: '← Back to sign in' },
    'forgot.erreurTelephone': { fr: 'Veuillez saisir votre numéro de téléphone.', en: 'Please enter your phone number.' },
    'forgot.erreurEnvoi': { fr: "Erreur lors de l'envoi du code. Réessayez.", en: 'Error sending the code. Please try again.' },
    'forgot.erreurCode6': { fr: 'Le code doit contenir 6 chiffres.', en: 'The code must contain 6 digits.' },
    'forgot.erreurCodeInvalide': { fr: 'Code incorrect ou expiré.', en: 'Incorrect or expired code.' },
    'forgot.erreurMdpCourt': { fr: 'Le mot de passe doit contenir au moins 6 caractères.', en: 'The password must be at least 6 characters long.' },
    'forgot.erreurReinit': { fr: 'Erreur lors de la réinitialisation.', en: 'Error while resetting the password.' },

    // --- Accueil (landing) ---
    'home.surTitre': { fr: 'Conformité CEMAC · Plafond mensuel Hors CEMAC', en: 'CEMAC compliance · Monthly non-CEMAC cap' },
    'home.h1Debut': { fr: 'Le plafond de chaque client,', en: 'Every client\'s cap,' },
    'home.h1Em': { fr: 'vérifié', en: 'verified' },
    'home.h1Fin': { fr: 'avant chaque transfert.', en: 'before every transfer.' },
    'home.pitch': { fr: "Saisissez le client, le montant, la destination — la plateforme calcule son cumul du mois et vous dit immédiatement si l'opération peut partir. Exécution, annulation motivée, bordereau avec QR code : toute votre activité, tracée.", en: 'Enter the client, amount and destination — the platform calculates their monthly total and instantly tells you whether the operation can proceed. Execution, motivated cancellation, receipt with QR code: all your activity, tracked.' },
    'home.btnAcceder': { fr: "Accéder à l'application", en: 'Access the application' },
    'home.mention1Valeur': { fr: '1 000 000 FCFA', en: '1,000,000 FCFA' },
    'home.mention1Label': { fr: 'plafond mensuel Hors CEMAC', en: 'monthly non-CEMAC cap' },
    'home.mention2Valeur': { fr: '6 pays CEMAC', en: '6 CEMAC countries' },
    'home.mention2Label': { fr: 'exemptés du plafond', en: 'exempt from the cap' },
    'home.mention3Valeur': { fr: 'Temps réel', en: 'Real time' },
    'home.mention3Label': { fr: 'bilan journalier par agent', en: 'daily summary per agent' },
    'home.demoTete': { fr: 'Vérification du plafond', en: 'Cap verification' },
    'home.demoOp': { fr: '250 000 FCFA → Canada · MoneyGram', en: '250,000 FCFA → Canada · MoneyGram' },
    'home.jaugeLib': { fr: 'sur 1 000 000 FCFA ce mois', en: 'out of 1,000,000 FCFA this month' },
    'home.demoVerdict': { fr: '✓ Transfert autorisé — reste 250 000 FCFA', en: '✓ Transfer authorized — 250,000 FCFA remaining' },
    'home.parcoursTitre': { fr: 'Trois gestes, zéro dépassement', en: 'Three steps, zero overrun' },
    'home.etape1Titre': { fr: 'Vérifier', en: 'Verify' },
    'home.etape1Texte': { fr: 'Le nom du client suffit : la plateforme retrouve son cumul mensuel, remplit sa fiche s\'il est déjà connu, et rend son verdict.', en: "The client's name is enough: the platform retrieves their monthly total, fills in their record if already known, and returns a verdict." },
    'home.etape2Titre': { fr: 'Exécuter', en: 'Execute' },
    'home.etape2Texte': { fr: "Opération autorisée ? Vous saisissez la référence du réseau et l'opération est enregistrée à votre nom et à votre agence.", en: "Operation authorized? You enter the network reference and the operation is recorded under your name and branch." },
    'home.etape3Titre': { fr: 'Justifier', en: 'Justify' },
    'home.etape3Texte': { fr: 'Bordereau imprimable avec QR code de vérification. Annulation ou rejet ? Toujours motivés, toujours tracés.', en: 'Printable receipt with a verification QR code. Cancellation or rejection? Always justified, always tracked.' },

    'home.avantagesSurTitre': { fr: 'Pourquoi TransFlow', en: 'Why TransFlow' },
    'home.avantagesTitre': { fr: 'Une plateforme pensée pour la conformité bancaire', en: 'A platform built for banking compliance' },
    'home.avantagesSousTitre': { fr: "Chaque fonctionnalité répond à une exigence réglementaire ou opérationnelle du réseau d'agences.", en: 'Every feature answers a regulatory or operational requirement of the branch network.' },
    'home.avantage1Titre': { fr: 'Conformité CEMAC', en: 'CEMAC compliance' },
    'home.avantage1Texte': { fr: 'Le plafond mensuel Hors CEMAC est calculé et vérifié automatiquement, sans risque d\'erreur humaine.', en: 'The monthly non-CEMAC cap is calculated and verified automatically, removing human error.' },
    'home.avantage2Titre': { fr: 'Sécurité des données', en: 'Data security' },
    'home.avantage2Texte': { fr: 'Authentification par jeton et accès par rôle protègent chaque opération et chaque agent.', en: 'Token authentication and role-based access protect every operation and every agent.' },
    'home.avantage3Titre': { fr: 'Multi-canal', en: 'Multi-channel' },
    'home.avantage3Texte': { fr: 'MoneyGram et Small World sont pris en charge nativement, avec un flux de vérification identique.', en: 'MoneyGram and Small World are natively supported, with an identical verification flow.' },
    'home.avantage4Titre': { fr: 'Traçabilité totale', en: 'Full traceability' },
    'home.avantage4Texte': { fr: 'Chaque vérification, exécution et annulation est horodatée et attribuée à l\'agent et à l\'agence.', en: 'Every check, execution and cancellation is timestamped and attributed to the agent and branch.' },

    'home.ctaTitre': { fr: 'Prêt à sécuriser vos transferts Hors CEMAC ?', en: 'Ready to secure your non-CEMAC transfers?' },
    'home.ctaTexte': { fr: 'Connectez-vous avec vos identifiants agent pour accéder à la plateforme.', en: 'Sign in with your agent credentials to access the platform.' },

    'home.footerTagline': { fr: 'Plateforme interne de suivi des transferts rapides Hors CEMAC, à usage des agences partenaires.', en: 'Internal platform for tracking non-CEMAC fast transfers, for use by partner branches.' },
    'home.footerLiens': { fr: 'Accès rapide', en: 'Quick access' },
    'home.pied': { fr: 'Afriland First Bank — plateforme à usage interne des agences partenaires', en: 'Afriland First Bank — internal platform for partner branches' },

    // --- Choix du canal ---
    'channel.etapeFinale': { fr: '● Étape finale', en: '● Final step' },
    'channel.titre': { fr: 'Choisissez votre moyen de distribution', en: 'Choose your distribution channel' },
    'channel.sousTitre': { fr: "Sélectionnez la plateforme sur laquelle vous opérez aujourd'hui.", en: 'Select the platform you are operating on today.' },
    'channel.retour': { fr: '← Retour à la connexion', en: '← Back to sign in' },

    // --- Vérification ---
    'verif.sectionIdentite': { fr: "IDENTITÉ DU CLIENT", en: "CLIENT IDENTITY" },
    'verif.sectionDetails': { fr: 'DÉTAILS DU TRANSFERT', en: 'TRANSFER DETAILS' },
    'verif.parcourir': { fr: 'Parcourir', en: 'Browse' },
    'verif.etape1': { fr: 'Informations', en: 'Information' },
    'verif.etape2': { fr: 'Confirmation', en: 'Confirmation' },
    'verif.etape3': { fr: 'Vérification', en: 'Verification' },
    'verif.etape4': { fr: 'Reçu', en: 'Receipt' },
    'verif.succesTitre': { fr: 'Transfert soumis avec succès', en: 'Transfer submitted successfully' },
    'verif.succesSous': { fr: 'Le transfert a été enregistré. Conservez la référence ci-dessous.', en: 'The transfer has been recorded. Keep the reference below.' },
    'verif.vers': { fr: 'FCFA vers', en: 'FCFA to' },
    'verif.reference': { fr: 'Référence', en: 'Reference' },
    'verif.referenceVerification': { fr: 'Référence de vérification', en: 'Verification reference' },
    'verif.imprimerBordereau': { fr: '🖨️ Imprimer le bordereau (PDF)', en: '🖨️ Print the receipt (PDF)' },
    'verif.nouveauTransfert': { fr: 'Nouveau transfert', en: 'New transfer' },
    'verif.labelNom': { fr: 'Nom du client', en: "Client's name" },
    'verif.labelNomSuffixe': { fr: '— tel que sur la pièce', en: '— as shown on the ID' },
    'verif.placeholderNom': { fr: 'Entrer le nom du client', en: "Enter the client's name" },
    'verif.clientConnu': { fr: 'Client déjà connu ? Cliquez pour remplir automatiquement :', en: 'Already a known client? Click to auto-fill:' },
    'verif.labelDateNaissance': { fr: 'Date de naissance', en: 'Date of birth' },
    'verif.placeholderDate': { fr: 'jj-mm-aaaa (tirets automatiques)', en: 'dd-mm-yyyy (auto dashes)' },
    'verif.labelNature': { fr: "Nature de la pièce d'identité", en: 'Type of ID document' },
    'verif.labelNumeroPiece': { fr: "N° de la pièce d'identité", en: 'ID document number' },
    'verif.placeholderNumero': { fr: 'Entrer le long numéro', en: 'Enter the full number' },
    'verif.labelMontant': { fr: 'Montant du transfert (FCFA)', en: 'Transfer amount (FCFA)' },
    'verif.placeholderMontant': { fr: 'Entrer le montant', en: 'Enter the amount' },
    'verif.labelPays': { fr: 'Pays de destination', en: 'Destination country' },
    'verif.selectionnerPays': { fr: 'Sélectionner un pays', en: 'Select a country' },
    'verif.apercuPiece': { fr: "Aperçu de la pièce d'identité", en: 'ID document preview' },
    'verif.glisserScan': { fr: 'Glissez le scan CNI / passeport ici (optionnel)', en: 'Drag the ID/passport scan here (optional)' },
    'verif.verificationEnCours': { fr: 'Vérification…', en: 'Verifying…' },
    'verif.verifierPlafond': { fr: 'Vérifier le plafond', en: 'Check the cap' },
    'verif.recapTitre': { fr: 'Le formulaire est-il bien rempli ?', en: 'Is the form filled in correctly?' },
    'verif.recapSous': { fr: 'Vérifiez les informations saisies avant de lancer la vérification du plafond.', en: 'Check the entered information before running the cap verification.' },
    'verif.champNom': { fr: 'NOM DU CLIENT', en: "CLIENT'S NAME" },
    'verif.champNaissance': { fr: 'DATE DE NAISSANCE', en: 'DATE OF BIRTH' },
    'verif.champNature': { fr: 'NATURE DE LA PIÈCE', en: 'ID TYPE' },
    'verif.champNumero': { fr: 'N° DE LA PIÈCE', en: 'ID NUMBER' },
    'verif.champMontant': { fr: 'MONTANT DU TRANSFERT', en: 'TRANSFER AMOUNT' },
    'verif.champPays': { fr: 'PAYS DE DESTINATION', en: 'DESTINATION COUNTRY' },
    'verif.modifier': { fr: '← Modifier', en: '← Edit' },
    'verif.valider': { fr: 'Valider', en: 'Confirm' },
    'verif.autorise': { fr: 'Transfert autorisé', en: 'Transfer authorized' },
    'verif.refuse': { fr: 'Transfert refusé', en: 'Transfer denied' },
    'verif.client': { fr: 'CLIENT', en: 'CLIENT' },
    'verif.destination': { fr: 'DESTINATION', en: 'DESTINATION' },
    'verif.naissance': { fr: 'NAISSANCE', en: 'DATE OF BIRTH' },
    'verif.numeroPiece': { fr: 'N° PIÈCE', en: 'ID NUMBER' },
    'verif.dernierTransfert': { fr: 'Dernier transfert Hors CEMAC', en: 'Last non-CEMAC transfer' },
    'verif.aucunTransfert': { fr: 'Aucun transfert', en: 'No transfer' },
    'verif.montantTransferable': { fr: 'MONTANT TRANSFÉRABLE CE MOIS', en: 'TRANSFERABLE AMOUNT THIS MONTH' },
    'verif.plafond': { fr: 'PLAFOND', en: 'CAP' },
    'verif.dejaUtilise': { fr: 'Déjà utilisé ·', en: 'Already used ·' },
    'verif.pctPlafond': { fr: '{pct}% du plafond', en: '{pct}% of the cap' },
    'verif.consigne': { fr: "Une fois la transaction exécutée, saisissez la référence de l'opération générée par la plateforme, puis soumettez.", en: 'Once the transaction is executed, enter the operation reference generated by the platform, then submit.' },
    'verif.placeholderRef': { fr: 'Référence plateforme de transfert', en: 'Transfer platform reference' },
    'verif.envoiEnCours': { fr: 'Envoi…', en: 'Sending…' },
    'verif.soumettre': { fr: 'Soumettre', en: 'Submit' },
    'verif.retourVerification': { fr: 'Retour à la vérification', en: 'Back to verification' },
    'verif.erreurPieceFormat': { fr: 'Le n° de pièce ne doit contenir que des lettres et des chiffres (sans espaces).', en: 'The ID number must contain only letters and digits (no spaces).' },
    'verif.erreurPieceCourt': { fr: 'N° de pièce trop court pour une pièce de type « {nature} » (minimum {min} caractères).', en: 'ID number too short for a document of type "{nature}" (minimum {min} characters).' },
    'verif.erreurCniFormat': { fr: "N° de CNI invalide : attendu 18 chiffres (ancienne carte) ou 2 lettres suivies de 8 chiffres (nouvelle carte).", en: 'Invalid ID number: expected 18 digits (old card) or 2 letters followed by 8 digits (new card).' },
    'verif.libelleNom': { fr: 'le nom du client', en: "the client's name" },
    'verif.libelleDate': { fr: 'la date de naissance (jj-mm-aaaa)', en: 'the date of birth (dd-mm-yyyy)' },
    'verif.libelleNature': { fr: 'la nature de la pièce', en: 'the ID type' },
    'verif.libellePiece': { fr: 'le n° de la pièce', en: 'the ID number' },
    'verif.libelleMontant': { fr: 'le montant', en: 'the amount' },
    'verif.libellePays': { fr: 'le pays de destination', en: 'the destination country' },
    'verif.erreurRenseigner': { fr: 'Veuillez renseigner : {champs}.', en: 'Please fill in: {champs}.' },
    'verif.erreurServeur': { fr: 'Impossible de joindre le serveur. Vérifiez que le backend est démarré (port 8080).', en: 'Unable to reach the server. Check that the backend is running (port 8080).' },
    'verif.erreurSession': { fr: 'Session expirée ou non autorisée. Veuillez vous déconnecter puis vous reconnecter.', en: 'Session expired or unauthorized. Please log out and sign in again.' },
    'verif.erreurVerification': { fr: 'Erreur lors de la vérification (code {code}). Réessayez.', en: 'Error during verification (code {code}). Please try again.' },
    'verif.erreurReference': { fr: "Veuillez saisir la référence de l'opération.", en: 'Please enter the operation reference.' },
    'verif.erreurExecution': { fr: "Impossible d'exécuter le transfert.", en: 'Unable to execute the transfer.' },

    // --- Historique / annulation / justificatifs (liste) ---
    'liste.placeholderRecherche': { fr: 'Rechercher un client, une référence…', en: 'Search a client, a reference…' },
    'liste.aucunTransfert': { fr: 'Aucun transfert à afficher.', en: 'No transfer to display.' },
    'liste.colCanal': { fr: 'Canal', en: 'Channel' },
    'liste.popupTitreAnnuler': { fr: 'Annuler ce transfert', en: 'Cancel this transfer' },
    'liste.popupTitreRejeter': { fr: 'Rejeter ce transfert', en: 'Reject this transfer' },
    'liste.popupReference': { fr: 'Référence', en: 'Reference' },
    'liste.motifLabelAnnulation': { fr: "Motif de l'annulation", en: 'Cancellation reason' },
    'liste.motifLabelRejet': { fr: 'Motif du rejet', en: 'Rejection reason' },
    'liste.obligatoire': { fr: '— obligatoire', en: '— required' },
    'liste.placeholderMotifAnnulation': { fr: 'Expliquez pourquoi cette opération est annulée (au moins 10 caractères)…', en: 'Explain why this operation is being cancelled (at least 10 characters)…' },
    'liste.placeholderMotifRejet': { fr: 'Expliquez pourquoi cette opération est rejetée (au moins 10 caractères)…', en: 'Explain why this operation is being rejected (at least 10 characters)…' },
    'liste.motifValide': { fr: '✓ Motif valide', en: '✓ Valid reason' },
    'liste.caracteresMinimum': { fr: '{n}/10 caractères minimum', en: '{n}/10 characters minimum' },
    'liste.envoiEnCours': { fr: 'Envoi…', en: 'Sending…' },
    'liste.confirmerAnnulation': { fr: "Confirmer l'annulation", en: 'Confirm cancellation' },
    'liste.confirmerRejet': { fr: 'Confirmer le rejet', en: 'Confirm rejection' },
    'liste.erreurChargement': { fr: 'Erreur lors du chargement des transferts.', en: 'Error loading transfers.' },
    'liste.erreurMotifCourt': { fr: 'Le motif doit contenir au moins 10 caractères.', en: 'The reason must contain at least 10 characters.' },
    'liste.erreurOperation': { fr: "Impossible d'effectuer cette opération.", en: 'Unable to complete this operation.' },

    // --- Détails ---
    'details.naturePiece': { fr: 'NATURE PIÈCE', en: 'ID TYPE' },
    'details.canal': { fr: 'CANAL', en: 'CHANNEL' },
    'details.agence': { fr: 'AGENCE', en: 'BRANCH' },
    'details.reference': { fr: 'RÉFÉRENCE', en: 'REFERENCE' },
    'details.dateTransfert': { fr: 'DATE DU TRANSFERT', en: 'TRANSFER DATE' },
    'details.cumulMois': { fr: 'CUMUL DU MOIS', en: 'MONTHLY TOTAL' },
    'details.faitPar': { fr: 'FAIT PAR (AGENT)', en: 'HANDLED BY (AGENT)' },
    'details.motif': { fr: 'MOTIF ({statut})', en: 'REASON ({statut})' },
    'details.retourHistorique': { fr: "← Retour à l'historique", en: '← Back to history' },
    'details.introuvable': { fr: 'Transfert introuvable.', en: 'Transfer not found.' },
    'details.erreurChargement': { fr: 'Erreur lors du chargement du transfert.', en: 'Error loading the transfer.' },

    // --- Bilan ---
    'bilan.executes': { fr: 'Transferts exécutés', en: 'Executed transfers' },
    'bilan.rejetes': { fr: 'Transferts rejetés', en: 'Rejected transfers' },
    'bilan.annules': { fr: 'Transferts annulés', en: 'Cancelled transfers' },
    'bilan.nonClotures': { fr: 'Non clôturés', en: 'Not closed' },
    'bilan.total': { fr: 'Total du jour', en: "Today's total" },
    'bilan.jour': { fr: 'Bilan du {jour}', en: 'Summary for {jour}' },
    'bilan.erreurChargement': { fr: 'Erreur lors du chargement du bilan.', en: 'Error loading the summary.' },

    // --- Communs ---
    'commun.rechercher': { fr: 'Rechercher', en: 'Search' },
    'commun.details': { fr: 'Détails', en: 'Details' },
    'commun.bordereau': { fr: 'Bordereau', en: 'Receipt' },
    'commun.annuler': { fr: 'Annuler', en: 'Cancel' },
    'commun.rejeter': { fr: 'Rejeter', en: 'Reject' },
    'commun.retour': { fr: 'Retour', en: 'Back' },
    'commun.motif': { fr: 'Motif', en: 'Reason' },
    'commun.client': { fr: 'Client', en: 'Client' },
    'commun.montant': { fr: 'Montant', en: 'Amount' },
    'commun.destination': { fr: 'Destination', en: 'Destination' },
    'commun.date': { fr: 'Date', en: 'Date' },
    'commun.statut': { fr: 'Statut', en: 'Status' },
    'commun.saisiPar': { fr: 'Saisi par', en: 'Entered by' },
    'commun.partenaire': { fr: 'Partenaire', en: 'Partner' },
    'commun.telephone': { fr: 'Numéro de téléphone', en: 'Phone number' },
    'commun.motDePasse': { fr: 'Mot de passe', en: 'Password' },
    'commun.email': { fr: 'Email', en: 'Email' },
    'commun.seConnecter': { fr: 'Se connecter', en: 'Sign in' },
    'commun.creerCompte': { fr: 'Créer un compte', en: 'Create an account' },
    'commun.selectionner': { fr: 'Sélectionner…', en: 'Select…' },
    'commun.copyright': { fr: '© 2026 Afriland First Bank · Usage interne', en: '© 2026 Afriland First Bank · Internal use' },
    'commun.erreurChamps': { fr: 'Veuillez renseigner tous les champs.', en: 'Please fill in all fields.' },
    'commun.erreurMdpDiff': { fr: 'Les mots de passe ne correspondent pas.', en: 'Passwords do not match.' },

    // --- Admin ---
    'admin.titre': { fr: 'Administration', en: 'Administration' },
    'admin.sousTitre': { fr: 'Partenaires et comptes utilisateurs', en: 'Partners and user accounts' },
    'admin.nouveauPartenaire': { fr: 'Nouveau partenaire', en: 'New partner' },
    'admin.nouvelUtilisateur': { fr: 'Nouvel utilisateur', en: 'New user' },
    'admin.creer': { fr: 'Créer', en: 'Create' },
  };

  t(cle: string, params?: Record<string, string | number>): string {
    const entree = this.dictionnaire[cle];
    let texte = entree ? entree[this.langue()] : cle;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        texte = texte.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      }
    }
    return texte;
  }

  basculer(): void {
    const nouvelle: Langue = this.langue() === 'fr' ? 'en' : 'fr';
    this.langue.set(nouvelle);
    localStorage.setItem('langue', nouvelle);
  }
}
